#:kivy 2.0.0

<MyView>:
    TabbedPanelItem:
        text: 'name'
        Accordion:
            orientation: 'vertical'
            # id: aa

            AccordionItem:
                id: aI
                
                RelativeLayout:
                    id: true_relative
                    size_hint: None, None
                    size: aI.container.size
                    # y: root.y-300

                    ScrollView:
                        do_scroll_x: True
                        do_scroll_y: True
                        BoxLayout:
                            canvas.before:
                                Color:
                                    rgba: 0, 1, 0, 1
                                Line:
                                    width: 2
                                    rectangle: self.x, self.y, self.width, self.height

                            orientation: 'vertical'
                            # height: root.height
                            # size_hint: .5, .5
                            # pos_hint: {'top': 0}
                            size_hint_y: .99
                            size_hint_x: .99
                            spacing: 10


                            # height: None

                            Button:
                                size_hint: .5, None
                                pos_hint: {'center_x': .5}
                                height: 50
                                text: "button 1"

                            Button:
                                size_hint: .5, None
                                pos_hint: {'center_x': .5}
                                height: 50
                                text: "button 2"
                            Button:
                                size_hint: .5, None
                                pos_hint: {'center_x': .5}
                                height: 50
                                text: "button 2"

                            # OMFG TO DIZALA
                            Widget:

            AccordionItem:
                ScrollView:

                    BoxLayout:
                        canvas.before:
                            Color:
                                rgba: 0, 1, 0, 1
                            Line:
                                width: 2
                                rectangle: self.x, self.y, self.width, self.height
                        orientation: 'vertical'
                        size_hint: 1, None
                        pos_hint: {'top': 1}

                        Button:
                            canvas.before:
                                Color:
                                    rgba: 0, 1, 0, 1
                                Line:
                                    width: 2
                                    rectangle: self.x, self.y, self.width, self.height
                            size_hint: .5, None
                            height: 50
                            text: "button 1"
                        Button:
                            size_hint: .5, None
                            height: 50
                            text: "button 2"